name: Task
description: Create a new task
title: "[Task]: "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        Create a new task with deadline and priority
  - type: input
    id: deadline
    attributes:
      label: Deadline
      description: When should this task be completed?
      placeholder: YYYY-MM-DD
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: Describe the task in detail
    validations:
      required: true
